In [2]:
import numpy as np
import pandas as pd

In [ ]:
arr = np.arange(10,25).reshape(3,5)
arr
df = pd.DataFrame(arr)
df

In [3]:
df = pd.DataFrame({
    "Id":[
        "Nestech_001",
        "Nestech_002",
        "Nestech_003",
        "Nestech_004",
        "Nestech_005",
        "Nestech_006",
        "Nestech_007",
        "Nestech_008",
        "Nestech_009",
        "Nestech_010"
    ],
    "Full Name":[
        "Nguyen Phu Trong",
        "Vo Van Thuong",
        "Nguyen Hoang Kieu Trinh",
        "Viktor Nguyen",
        "Clint Nguyen",
        "Nguyen Van Toan",
        "Kha Kim Bao Han",
        "Pham Le Tram Anh",
        "Ba Hoang Kim Thinh",
        "Giap Phi Hoang",
    ],
    "Sex":[
        "M",
        "M",
        "F",
        "M",
        "M",
        "M",
        "F",
        "F",
        "F",
        "M",
    ],
    "Note":[
        "Lop Truong",
        "Pho Lop Truong",
        "",
        "",
        "",
        "",
        "Ex",
        "Ex",
        "Ex",
        "Y Thuc Kem",
    ]
}, columns=["Id", "Full Name", "Sex", "Note"])

df

            Id                Full Name Sex            Note
0  Nestech_001         Nguyen Phu Trong   M      Lop Truong
1  Nestech_002            Vo Van Thuong   M  Pho Lop Truong
2  Nestech_003  Nguyen Hoang Kieu Trinh   F
3  Nestech_004            Viktor Nguyen   M
4  Nestech_005             Clint Nguyen   M
5  Nestech_006          Nguyen Van Toan   M
6  Nestech_007          Kha Kim Bao Han   F              Ex
7  Nestech_008         Pham Le Tram Anh   F              Ex
8  Nestech_009       Ba Hoang Kim Thinh   F              Ex
9  Nestech_010           Giap Phi Hoang   M      Y Thuc Kem